### ISSUE TITLE
Contribute your NODE APPS here

### ISSUE THREAD

**Issue by shreyanshiitb** [desiredeveloper/Node-Apps#1]
#HACKTOBERFEST
contribute and raise Pull requests

**Comment by anonewb** [comment]
> #HACKTOBERFEST
> contribute and raise Pull requests

Done!!

**Comment by LuisPaGarcia** [comment]
I just added some features to the repo.

**Comment by LuisPaGarcia** [comment]
Any update?

**Comment by LuisPaGarcia** [comment]
Just updated the principal README.md and the .gitignore
